DUNGEONS = {
    "Kardorim": {"dungeon": "Crypte de Kardorim", "lvl": 10, "points": 67, "index": 0},
    # "Kardorim": {"dungeon": "Crypte de Kardorim", "lvl": 10, "points": 1, "index": 0},
    "Tournesol Affamé": {"dungeon": "Grange du Tournesol Affamé", "lvl": 20, "points": 2, "index": 1},
    "Mob l'Éponge": {"dungeon": "Château Ensablé", "lvl": 20, "points": 2, "index": 2},
    "Bouftou Royal": {"dungeon": "Cour du Bouftou Royal", "lvl": 30, "points": 3, "index": 3},
    "Kankreblath": {"dungeon": "Cache de Kankreblath", "lvl": 40, "points": 4, "index": 4},
    "Scarabosse Doré": {"dungeon": "Scarafeuilles", "lvl": 40, "points": 4, "index": 5},
    "Chafer Rônin": {"dungeon": "Squelettes", "lvl": 40, "points": 4, "index": 6},
    "Batofu": {"dungeon": "Tofus", "lvl": 40, "points": 4, "index": 7},
    "Directeur Grunob": {"dungeon": "Akadémie des Gobs", "lvl": 40, "points": 4, "index": 8},
    "Bworkette": {"dungeon": "Bworks", "lvl": 50, "points": 5, "index": 9},
    "Coffre des Forgerons": {"dungeon": "Forgerons", "lvl": 50, "points": 5, "index": 10},
    "Corailleur Magistral": {"dungeon": "Grotte Hesque", "lvl": 50, "points": 5, "index": 11},
    "Shin Larve": {"dungeon": "Larves", "lvl": 50, "points": 5, "index": 12},
    "Boostache": {"dungeon": "Maison Fantôme", "lvl": 50, "points": 5, "index": 13},
    "Kwakwa": {"dungeon": "Nid du Kwakwa", "lvl": 50, "points": 5, "index": 14},
    "Sapik": {"dungeon": "Nowel", "lvl": 50, "points": 5, "index": 15},
    "Rakoopieur": {"dungeon": "Refuge Sylvestre", "lvl": 50, "points": 5, "index": 16},

    "Wa Wabbit": {"dungeon": "Château du Wa Wabbit", "lvl": 60, "points": 250, "index": 17},
    # "Wa Wabbit": {"dungeon": "Château du Wa Wabbit", "lvl": 60, "points": 6, "index": 17},
    "Blop Coco Royal": {"dungeon": "Clos des Blops", "lvl": 60, "points": 6, "index": 18},
    "Blop Griotte Royal": {"dungeon": "Clos des Blops", "lvl": 60, "points": 6, "index": 19},
    "Blop Indigo Royal": {"dungeon": "Clos des Blops", "lvl": 60, "points": 6, "index": 20},
    "Blop Reinette Royal": {"dungeon": "Clos des Blops", "lvl": 60, "points": 6, "index": 21},
    "Gelée Royales": {"dungeon": "Gelaxième dimension", "lvl": 60, "points": 12, "index": 22},
    "Kanniboul Ebil": {"dungeon": "Village Kanniboul", "lvl": 60, "points": 6, "index": 23},
    "Mawabouaino": {"dungeon": "Fonderie des Waddicts", "lvl": 60, "points": 6, "index": 24},
    "Gourlo le Terrible": {"dungeon": "Cale de l'Arche d'Otomai", "lvl": 70, "points": 7, "index": 25},
    "Nelween": {"dungeon": "Laboratoire de Brumen Tinctorias", "lvl": 70, "points": 7, "index": 26},
    "Craqueleur Légendaire": {"dungeon": "Pitons Rocheux des Craqueleurs", "lvl": 70, "points": 7, "index": 27},
    "Draegnerys": {"dungeon": "Épreuve de Draegnerys", "lvl": 70, "points": 7, "index": 28},
    "Wa Wobot": {"dungeon": "Terrier du Wa Wabbit", "lvl": 80, "points": 8, "index": 29},
    "Mantiscore": {"dungeon": "Cimetière des Mastodontes", "lvl": 90, "points": 9, "index": 30},
    "Reine Nyée": {"dungeon": "Antre de la Reine Nyée", "lvl": 90, "points": 9, "index": 31},
    "Chouque": {"dungeon": "Bateau du Chouque", "lvl": 90, "points": 9, "index": 32},
    "Abraknyde Ancestral": {"dungeon": "Domaine Ancestral", "lvl": 90, "points": 9, "index": 33},
    "Choudini": {"dungeon": "Chapiteau des Magik Riktus", "lvl": 90, "points": 9, "index": 34},
    "Dragon Cochon": {"dungeon": "Antre du Dragon Cochon", "lvl": 100, "points": 10, "index": 35},
    "Meulou": {"dungeon": "Tanière du Meulou", "lvl": 100, "points": 10, "index": 36},
    "Koulosse": {"dungeon": "Caverne du Koulosse", "lvl": 100, "points": 10, "index": 37},
    "Mallefisk": {"dungeon": "Fabrique de Malléfisk", "lvl": 100, "points": 10, "index": 38},
    "Moon": {"dungeon": "Arbre de Moon", "lvl": 100, "points": 10, "index": 39},
    "Halouine": {"dungeon": "Potager d'Halouine", "lvl": 100, "points": 10, "index": 40},
    "Maître des Pantins": {"dungeon": "Théâtre de Dramak", "lvl": 100, "points": 10, "index": 41},
    "Kharnozor": {"dungeon": "Repaire du Kharnozor", "lvl": 100, "points": 10, "index": 42},

    "Maître Corbac": {"dungeon": "Bibliothèque du Maître Corbac", "lvl": 110, "points": 780, "index": 43},
    # "Maître Corbac": {"dungeon": "Bibliothèque du Maître Corbac", "lvl": 110, "points": 11, "index": 43},
    "Papa Nowel": {"dungeon": "Caverne de Nowel", "lvl": 110, "points": 11, "index": 44},
    "Rasboul Majeur": {"dungeon": "Goulet du Rasboul", "lvl": 110, "points": 11, "index": 45},
    "Pounicheur": {"dungeon": "Miausolée du Pounicheur", "lvl": 110, "points": 11, "index": 46},
    "Damadrya": {"dungeon": "Bambusaie de Damadrya", "lvl": 110, "points": 11, "index": 47},
    "Rat Blanc": {"dungeon": "Garde-manger du Rat Blanc", "lvl": 110, "points": 11, "index": 48},
    "Rat Noir": {"dungeon": "Sousouricière du Rat Noir", "lvl": 110, "points": 11, "index": 49},
    "Blop Multicolore": {"dungeon": "Antre du Blop Multicolore Royal", "lvl": 120, "points": 12, "index": 50},
    "Fraktale": {"dungeon": "Mégalithe de Fraktale", "lvl": 120, "points": 12, "index": 51},
    "Minotoror": {"dungeon": "Centre du Labyrinthe du Minotoror", "lvl": 120, "points": 12, "index": 52},
    "Skeunk": {"dungeon": "Repaire de Skeunk", "lvl": 120, "points": 12, "index": 53},
    "Crocabulia": {"dungeon": "Antre de Crocabulia", "lvl": 120, "points": 12, "index": 54},
    "Royalmouth": {"dungeon": "Serre du Royalmouth", "lvl": 120, "points": 12, "index": 55},
    "Tofu Royal": {"dungeon": "Tofulailler Royal", "lvl": 120, "points": 12, "index": 56},
    "Haute Truche": {"dungeon": "Volière de la Haute Truche", "lvl": 130, "points": 13, "index": 57},
    "Croqueleur": {"dungeon": "Croquanterie", "lvl": 130, "points": 13, "index": 58},
    "El Piko": {"dungeon": "Caverne d'El Piko", "lvl": 130, "points": 13, "index": 59},
    "Tanukoui San": {"dungeon": "Atelier du Tanukoui San", "lvl": 130, "points": 13, "index": 60},
    "Nagate": {"dungeon": "Vallée de la Dame des eaux", "lvl": 130, "points": 13, "index": 61},
    "Chêne Mou": {"dungeon": "Clairière du Chêne Mou", "lvl": 140, "points": 14, "index": 62},
    "Mansot Royal": {"dungeon": "Excavation du Mansot Royal", "lvl": 140, "points": 14, "index": 63},
    "Tynril": {"dungeon": "Laboratoire du Tynril", "lvl": 140, "points": 14, "index": 64},
    "Founoroshi": {"dungeon": "Fabrique de foux d'artifice", "lvl": 140, "points": 14, "index": 65},
    "Hanshi et Shihan": {"dungeon": "Dojo du Vent", "lvl": 140, "points": 14, "index": 66},
    "Ben le Ripate": {"dungeon": "Épave du Grolandais violent", "lvl": 150, "points": 15, "index": 67},
    "Phossile": {"dungeon": "Galerie du Phossile", "lvl": 150, "points": 15, "index": 68},
    "Sphincter Cell": {"dungeon": "Repaire de Sphincter Cell", "lvl": 150, "points": 15, "index": 69},
    "Hell Mina": {"dungeon": "Tertre du long sommeil", "lvl": 150, "points": 15, "index": 70},

    "Kimbo": {"dungeon": "Canopée du Kimbo", "lvl": 160, "points": 1300, "index": 71, "hard": False},
    # "Kimbo": {"dungeon": "Canopée du Kimbo", "lvl": 160, "points": 16, "index": 71, "hard": False},
    "Kanigroula": {"dungeon": "Grotte de Kanigroula", "lvl": 160, "points": 16, "index": 72, "hard": False},
    "Obsidiantre": {"dungeon": "Hypogée de l'Obsidiantre", "lvl": 160, "points": 16, "index": 73, "hard": False},
    "Minotot": {"dungeon": "Minotot", "lvl": 160, "points": 16, "index": 74, "hard": False},
    "Ush Galesh": {"dungeon": "Plateau de Ush", "lvl": 160, "points": 16, "index": 75, "hard": False},
    "Shogun Tofugawa": {"dungeon": "Tombe du Shogun Tofugawa", "lvl": 160, "points": 16, "index": 76, "hard": False},
    "XLII": {"dungeon": "Horologium de XLII", "lvl": 170, "points": 17, "index": 77, "hard": False},
    "Tengu Givrefoux": {"dungeon": "Tanière Givrefoux", "lvl": 170, "points": 17, "index": 78, "hard": False},
    "Père Ver": {"dungeon": "Boyau du Père Ver", "lvl": 170, "points": 17, "index": 79, "hard": False},
    "Koumiho": {"dungeon": "Demeure des Esprits", "lvl": 170, "points": 17, "index": 80, "hard": False},
    "Korriandre": {"dungeon": "Antre du Korriandre", "lvl": 180, "points": 18, "index": 81, "hard": False},
    "Kralamoure Géant": {"dungeon": "Antre du Kralamoure Géant", "lvl": 180, "points": 18, "index": 82, "hard": False},
    "Bworker": {"dungeon": "Grotte du Bworker", "lvl": 180, "points": 18, "index": 83, "hard": False},
    "Toxoliath": {"dungeon": "Cave du Toxoliath", "lvl": 180, "points": 18, "index": 84, "hard": False},
    "Ougah": {"dungeon": "Temple du Grand Ougah", "lvl": 180, "points": 18, "index": 85, "hard": False},
    "Père Fwetar": {"dungeon": "Maison du Papa Nowel", "lvl": 180, "points": 18, "index": 86, "hard": False},
    "Glourséleste": {"dungeon": "Antichambre des Gloursons", "lvl": 190, "points": 19, "index": 87, "hard": False},
    "Kolosso": {"dungeon": "Cavernes du Kolosso", "lvl": 190, "points": 19, "index": 88, "hard": False},
    "Grolloum": {"dungeon": "Mine de Sakai", "lvl": 190, "points": 19, "index": 89, "hard": False},
    "Ombre": {"dungeon": "Pyramide d'Ombre", "lvl": 190, "points": 19, "index": 90, "hard": False},
    "Comte Razof": {"dungeon": "Camp du Comte Razof", "lvl": 190, "points": 19, "index": 91, "hard": False},
    "Barbéryl Clochecuivre": {"dungeon": "Bastion des Marteaux-Aigris", "lvl": 190, "points": 19, "index": 92, "hard": False},
    "Merkator": {"dungeon": "Aquadôme de Merkator", "lvl": 200, "points": 20, "index": 93, "hard": False},
    "Comte Harebourg": {"dungeon": "Comte Harebourg", "lvl": 200, "points": 20, "index": 94, "hard": False},
    "Missiz Frizz": {"dungeon": "Forgefroide de Missiz Frizz", "lvl": 200, "points": 20, "index": 95, "hard": False},
    "Nileza": {"dungeon": "Laboratoire de Nileza", "lvl": 200, "points": 20, "index": 96, "hard": False},
    "Vortex": {"dungeon": "Œil de Vortex", "lvl": 200, "points": 20, "index": 97, "hard": False},
    "Roi Nidas": {"dungeon": "Palais du Roi Nidas", "lvl": 200, "points": 20, "index": 98, "hard": False},
    "Klime": {"dungeon": "Salons privés de Klime", "lvl": 200, "points": 20, "index": 99, "hard": False},
    "Sylargh": {"dungeon": "Transporteur de Sylargh", "lvl": 200, "points": 20, "index": 100, "hard": False},
    "Reine des Voleurs": {"dungeon": "Trône de la Cour Sombre", "lvl": 200, "points": 20, "index": 101, "hard": False},
    "Protozorreur": {"dungeon": "Ventre de la Baleine", "lvl": 200, "points": 20, "index": 102, "hard": False},
    "Chaloeil": {"dungeon": "Défi du Chaloeil", "lvl": 200, "points": 20, "index": 103, "hard": False},
    "Larve de Koutoulou": {"dungeon": "Temple de Koutoulou", "lvl": 200, "points": 20, "index": 104, "hard": False},
    "Capitaine Meno": {"dungeon": "Vaisseau du Capitaine Meno", "lvl": 200, "points": 20, "index": 105, "hard": False},
    "Dantinéa": {"dungeon": "Palais de Dantinéa", "lvl": 200, "points": 20, "index": 106, "hard": False},

    "Solar": {"dungeon": "Tour de Solar", "lvl": 200, "points": 2500, "index": 107, "hard": True},
    # "Solar": {"dungeon": "Tour de Solar", "lvl": 200, "points": 22, "index": 107, "hard": True},
    "Bethel": {"dungeon": "Tour de Bethel", "lvl": 200, "points": 22, "index": 108, "hard": True},
    "Dazak Martegel": {"dungeon": "Brasserie du roi Dazak", "lvl": 200, "points": 22, "index": 109, "hard": True},
    "Malice": {"dungeon": "Malice", "lvl": 200, "points": 22, "index": 110, "hard": True},
    "Tal Kasha": {"dungeon": "Chambre de Tal Kasha", "lvl": 200, "points": 22, "index": 111, "hard": True},
    "Prétresse de Kao": {"dungeon": "Temple du dieu Kao", "lvl": 200, "points": 22, "index": 112, "hard": True},
    "Ilyzaelle": {"dungeon": "Belvédère d'Ilyzaelle", "lvl": 200, "points": 22, "index": 113, "hard": True},
    "Anerice la Shushess": {"dungeon": "Manoir des Katrepat", "lvl": 200, "points": 22, "index": 114, "hard": True},
    "Torkélonia": {"dungeon": "Sanctuaire de Torkélonia", "lvl": 200, "points": 22, "index": 115, "hard": True},
    "Misère": {"dungeon": "Sentence de la Balance", "lvl": 200, "points": 25, "index": 116, "hard": True},
    "Servitude": {"dungeon": "Fers de la Tyrannie", "lvl": 200, "points": 25, "index": 117, "hard": True},
    "Guerre": {"dungeon": "Trône de sang", "lvl": 200, "points": 25, "index": 118, "hard": True},
    "Corruption": {"dungeon": "Arbre de mort", "lvl": 200, "points": 25, "index": 119, "hard": True},
    "Reine Amirukam": {"dungeon": "Souvenir d'Imagiro", "lvl": 200, "points": 27, "index": 120, "hard": True},
    "Roi Imagami": {"dungeon": "Mémoire d'Orukam", "lvl": 200, "points": 27, "index": 121, "hard": True},
    "Kabahal": {"dungeon": "Rituel de Kabahal", "lvl": 200, "points": 27, "index": 122, "hard": True},
    "L'Éternel Conflit": {"dungeon": "Bataille de l'Aurore Pourpre", "lvl": 200, "points": 27, "index": 123, "hard": True},
    "Draguisla Bonita": {"dungeon": "Draguisla Bonita", "lvl": 200, "points": 27, "index": 124, "hard": True},
    "Belladone": {"dungeon": "Chambre des maléfices", "lvl": 200, "points": 27, "index": 125, "hard": True},
    "Cire Momore": {"dungeon": "Caverne de Cire Momore", "lvl": 200, "points": 27, "index": 126, "hard": True},
    "Corruption, Guerre, Misère, Servitude": {"dungeon": "Tempête de l'Eliocalypse", "lvl": 200, "points": 30, "index": 127, "hard": True}
}
